"""added new columns

Revision ID: 4479e1f1bf02
Revises: ffc124390ce9
Create Date: 2021-08-02 12:53:33.947328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4479e1f1bf02'
down_revision = 'ffc124390ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newlead', sa.Column('status', sa.String(length=64), nullable=True))
    op.add_column('newlead', sa.Column('comment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newlead', 'comment')
    op.drop_column('newlead', 'status')
    # ### end Alembic commands ###
