"""Python_Quiz

Revision ID: 5040d58677b2
Revises: 7a4b07f6d243
Create Date: 2021-01-21 18:44:17.947176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5040d58677b2'
down_revision = '7a4b07f6d243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('python_quiz', sa.Column('answer', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('python_quiz', sa.Column('option_a', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('option_b', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('option_c', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('option_d', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('question', sa.String(length=512), nullable=True))
    op.add_column('python_quiz', sa.Column('tag', sa.String(length=512), nullable=True))
    op.drop_column('python_quiz', 'field2')
    op.drop_column('python_quiz', 'field7')
    op.drop_column('python_quiz', 'field5')
    op.drop_column('python_quiz', 'field1')
    op.drop_column('python_quiz', 'field3')
    op.drop_column('python_quiz', 'field6')
    op.drop_column('python_quiz', 'field8')
    op.drop_column('python_quiz', 'field4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('python_quiz', sa.Column('field4', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field8', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field6', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field3', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field1', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field5', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field7', sa.TEXT(), nullable=True))
    op.add_column('python_quiz', sa.Column('field2', sa.TEXT(), nullable=True))
    op.drop_column('python_quiz', 'tag')
    op.drop_column('python_quiz', 'question')
    op.drop_column('python_quiz', 'option_d')
    op.drop_column('python_quiz', 'option_c')
    op.drop_column('python_quiz', 'option_b')
    op.drop_column('python_quiz', 'option_a')
    op.drop_column('python_quiz', 'id')
    op.drop_column('python_quiz', 'answer')
    # ### end Alembic commands ###
