"""Creating Question Bank

Revision ID: da822d43349f
Revises: 79ed9538a4ad
Create Date: 2021-01-06 14:24:54.061782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da822d43349f'
down_revision = '79ed9538a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('python_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=512), nullable=True),
    sa.Column('option_a', sa.String(length=512), nullable=True),
    sa.Column('option_b', sa.String(length=512), nullable=True),
    sa.Column('option_c', sa.String(length=512), nullable=True),
    sa.Column('option_d', sa.String(length=512), nullable=True),
    sa.Column('answer', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('python_quiz')
    # ### end Alembic commands ###
